# Generated by Django 5.1.7 on 2025-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_recomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='recomment',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
